# Generated by Django 5.1.2 on 2024-10-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='profil_photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
