# Generated by Django 5.1.2 on 2024-10-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0002_userregister_profil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='profil_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
