# Generated by Django 5.1.2 on 2024-10-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0004_alter_userregister_profil_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregister',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregister',
            name='profession',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregister',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
