# Generated by Django 5.1.2 on 2024-10-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0005_userregister_address_userregister_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
