# Generated by Django 5.1.2 on 2024-10-26 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0006_userregister_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(blank=True, max_length=255, null=True)),
                ('spiritual_belief', models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Atheist', 'Atheist'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=100, null=True)),
                ('future_goals', models.TextField(blank=True, null=True)),
                ('career_ambition', models.CharField(blank=True, choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=100, null=True)),
                ('openness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Curiosity and openness (1-5)')),
                ('humor_sense', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Sense of humor (1-5)')),
                ('confidence', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Confidence level (1-5)')),
                ('communication_style', models.CharField(blank=True, choices=[('Frequent', 'Frequent'), ('Occasional', 'Occasional'), ('Infrequent', 'Infrequent')], max_length=100, null=True)),
                ('listening_skills', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Listening skills (1-5)')),
                ('lifestyle', models.CharField(blank=True, choices=[('Early Bird', 'Early Bird'), ('Night Owl', 'Night Owl'), ('Flexible', 'Flexible')], max_length=100, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_activity_level', models.CharField(blank=True, choices=[('Active', 'Active'), ('Moderate', 'Moderate'), ('Sedentary', 'Sedentary')], max_length=100, null=True)),
                ('adaptability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Adaptability (1-5)')),
                ('conflict_management', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Conflict management (1-5)')),
                ('kindness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Kindness (1-5)')),
                ('empathy', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Empathy (1-5)')),
                ('emotional_maturity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Emotional maturity (1-5)')),
                ('resilience', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Resilience (1-5)')),
                ('financial_management', models.CharField(blank=True, choices=[('Saver', 'Saver'), ('Spender', 'Spender'), ('Balanced', 'Balanced')], max_length=100, null=True)),
                ('preferred_appearance', models.TextField(blank=True, help_text='Physical attributes that are preferred', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
