# Generated by Django 5.1.2 on 2024-10-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0009_remove_userprofile_adaptability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
