# Generated by Django 5.1.2 on 2024-10-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0011_userprofile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='values',
        ),
    ]
