# Generated by Django 5.1.2 on 2024-10-27 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0013_delete_userprofile_userregister_spiritual_belief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nerveux', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('nice', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('generous', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('likes_outings', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('frugal', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('misspent', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('available', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('smoker', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('drinks_wine', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('chapel', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('regular_prayer', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('has_car', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('has_house', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('has_bank_account', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('riche', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('polygamous_relationships', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WantedCaracteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nerveux', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('nice', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('generous', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('likes_outings', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('frugal', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('misspent', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('available', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('smoker', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('drinks_wine', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('chapel', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('regular_prayer', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('has_car', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('has_house', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('has_bank_account', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('riche', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('polygamous_relationships', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
