# Generated by Django 5.1.2 on 2024-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0014_caracteres_wantedcaracteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteres',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wantedcaracteres',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
