# Generated by Django 5.1.2 on 2024-10-28 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_tun', '0015_caracteres_score_wantedcaracteres_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('state', models.CharField(choices=[('confirmed', 'confirmed'), ('pending', 'pending'), ('refused', 'refused'), ('success', 'success')], max_length=100)),
                ('user_asked_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_requested', to=settings.AUTH_USER_MODEL)),
                ('user_to_confirm_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
